    - name: Remove "ocsinventory-agent" se tiver instalado
      apt:
        name: ocsinventory-agent
        state: absent 
      when: ansible_distribution == 'Ubuntu'


    - name: Importar Chave
      apt_key:
        url: http://deb.ocsinventory-ng.org/pubkey.gpg
        state: present
      when: ansible_distribution == 'Ubuntu' 


    - name: Remove "ocsinventory-agent" se tiver instalado no Centos
      yum:
        name: ocsinventory-agent
        state: absent
      when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] == '7'


    - name: Instala repo atualizado para o agente do OCS
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        - https://rpm.ocsinventory-ng.org/ocsinventory-release-latest.el7.ocs.noarch.rpm
      when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] == '7'


    - name: Instala ocs agent 2.8
      yum:
        name: ocsinventory-agent
        state: latest
      when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] == '7' 
      

    - name: Adiciona repositorio da versao mais recente
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] http://deb.ocsinventory-ng.org/ubuntu/ bionic main
        state: present
        filename: ocsinventory.list
      when: ansible_distribution == 'Ubuntu'

    - name: Atualiza o Cache
      apt:
        update_cache: yes
      when: ansible_distribution == 'Ubuntu' 


    - name: Instala o  agente OCS
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - ocsinventory-agent
      when: ansible_distribution == 'Ubuntu'



    - name: Instala repositorio Epel no Centos
      yum:
        name: epel-release
        state: latest
      when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] == '7'


    - name: Copia o repo atualizado
      copy:
        src: epel.repo
        dest: /etc/yum.repos.d
        force: yes 
      when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] == '7'



    - name: Remove a entrada no_proxy
      lineinfile:
        path: /etc/environment
        regex: '^export no_proxy'
        state: absent

    - name: Insere a linha export no_proxy com as excessoes
      lineinfile:
        path: /etc/environment
        line: export no_proxy=localhost,127.0.0.0/8,.grupoaec.com.br
        insertbefore: EOF


    
#    - name: Atualiza todos os pacotes do servidor para ultima versao
#      apt: upgrade=dist
#      when: ansible_distribution == 'Ubuntu'


    - name: Cria o arquivo de configuracao do OCS
      template: src=ocsinventory-agent.cfg.j2 dest=/etc/ocsinventory-agent/ocsinventory-agent.cfg
      when: ansible_distribution == 'Ubuntu'


    - name: Cria o arquivo de configuracao do OCS
      template: src=ocsinventory-agent.cfg.j2 dest=/etc/ocsinventory/ocsinventory-agent.cfg
      when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] == '7'



    - name: Remove a entrada no_proxy no arquivo /etc/environment
      lineinfile:
        path: /etc/environment
        regex: '^export no_proxy'
        state: absent

    - name: Insere a linha export no_proxy com as excessoes
      lineinfile: 
        path: /etc/environment
        line: export no_proxy=localhost,127.0.0.0/8,.grupoaec.com.br
        insertbefore: EOF


    - name: Cria o arquivo de crontab
      template: src=ocsagent.j2 dest=/etc/cron.d/ocsagent

    - name: Executa inventario No Ubuntu
      shell: /usr/bin/ocsinventory-agent --force
      when: ansible_distribution == 'Ubuntu' 


    - name: Executa inventario No Centos
      shell: /usr/sbin/ocsinventory-agent --force
      when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] == '7'





    





 

       

    
      
