- name: Nao atualiza o pacote do docker e containerd
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io


- name: Remove repositorios de terceiros
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/sources.list.d/docker.list
    - /etc/apt/sources.list.d/wazuh.list
  tags: remove_repo


- name: Remove chave dos respositorios de terceiros
  ansible.builtin.apt_key:
    id: "{{item}}"
    file: /etc/apt/trusted.gpg
    state: absent
  loop:
    - 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    - 0DCFCA5547B19D2A6099506096B3EE5F29111145 
  tags: remove_key


- name: Instala o pacote para gerar atualizacao automatica de seguranca somente
  apt: name=unattended-upgrades state=present


- name: Faz a atualização do cache
  apt: update_cache=yes



- name: Altera permissao por seguranca do grub
  ansible.builtin.file:
    path: /boot/grub/grub.cfg
    owner: root
    group: root
    mode: '0600'
  tags: perm



- name: Desativa servicos desnecessarios
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  loop:
  -  portmap
  -  rpcbind.socket
  tags: desativa

- name: Kernel parameters
  sysctl:
    name: "{{ item }}"
    value: '0'
    sysctl_set: yes
    state: present
    reload: yes
  loop: 
    - net.ipv4.conf.all.accept_redirects
    - net.ipv4.conf.default.accept_redirects
    - net.ipv4.tcp_timestamps
  tags: kernel


- name: Install a list of packages
  apt:
    pkg:
    - auditd
#    - audispd-plugins
  tags: plugin



- name: Configura regras e reinicia o servico do auditd
  template: src=audit.rules.j2 dest=/etc/audit/rules.d/audit.rules
  notify: restart auditd
  tags: service



- name: Adiciona tarefa de atualizacao de seguranca 
  ansible.builtin.cron:
    name: "Executa update de seguranca"
    minute: "01"
    hour: "01"
    day: "*"
    month: "*"
    weekday: "6"
    job: "sudo /usr/bin/unattended-upgrade -v"




