
    - name: Cria o arquivo de definicao limits
      template: src=limits.conf.j2 dest=/etc/security/limits.conf



    - name: Cria o arquivo de definicao kernet
      template: src=95-kong-specific.conf.j2 dest=/etc/sysctl.d/95-kong-specific.conf



    - name: Recarrega o sysct
      shell: | 
        sysctl -p --system
#        sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
#        echo "deb https://kong.bintray.com/kong-deb `lsb_release -sc` main" | sudo tee -a /etc/apt/sources.list


    - name: Adiciona chave do repo do Postgres
      ansible.builtin.apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present
      tags: add_postgres1


    - name: Adiciona repo postgres
      ansible.builtin.apt_repository:
        repo:  deb http://apt.postgresql.org/pub/repos/apt/ focal-pgdg main
        state: present
      tags: add_postres2


    - name: Adiciona repo do kong
      ansible.builtin.apt_repository:
        repo: deb https://kong.bintray.com/kong-deb/ focal main
        state: present
      tags: add_repo_kong



    - name: Adiciona chave do repo do kong
      ansible.builtin.apt_key:
        url: https://ftp-master.debian.org/keys/archive-key-6.0.asc
        state: present
      tags: add_key_kong



    - name: Download foo.conf
      get_url:
        url: https://bintray.com/user/downloadSubjectPublicKey?username=bintray
        dest: /etc/bintray.key
      tags: add_key1


    - name:  Add Apt signing key on remote server to keyring
      apt_key:
        file: /etc/bintray.key
        state: present
      tags: add_key2


    - name: Atualiza o cache 
      apt:
        update_cache: yes

    - name: Instala os pacotes base
      apt:
        pkg:
        - build-essential
        - net-tools 
        - curl
        - git
        - software-properties-common
        - openssl 
        - libpcre3 
        - postgresql-9.6 
        - libpcre3-dev 
        - procps 
        - perl 
        - apt-transport-https
        - python3-pip
        - python3-docker
        - kong
      tags: instala

    
    - name: Inicia o postgres
      service:
        enabled: yes
        name: postgresql
        state: restarted


    - name: Instala pacotes pip
      pip:
        name: ['psycopg2-binary']
        state: latest
#     with_items:
#       - psycopg2-binary
#       - docker
         
#       name: 
#         - psycopg2-binary
#         - docker
      tags: pip


    - name: Cria o usuario kong
      postgresql_user:
        login_user: postgres
        db: postgres
        password: "portprd@aec"
        name: kong
      become: true
      become_user: postgres

    - name: Cria o banco de dados chamado kong
      postgresql_db:
        login_user: postgres
        name: "kong"
        state: present
        owner: kong
      become: true
      become_user: postgres


    - name: Cria o usuario konga
      postgresql_user:
        login_user: postgres
        db: postgres
        password: "portprd@aec"
        name: konga
      become: true
      become_user: postgres

    - name: Cria o banco de dados chamado konga
      postgresql_db:
        login_user: postgres
        name: "konga"
        state: present
        owner: konga
      become: true
      become_user: postgres



    - name: Cria a configuracao padrao do kong
      template: src=kong.conf.j2 dest=/etc/kong/kong.conf


    - name: Realiza a copia dos certificados
      copy:
        src: /etc/ansible/roles/install_kong/certs
        dest: /etc/kong/


    - name: Inicia o kong
      shell: | 
        kong migrations bootstrap -c /etc/kong/kong.conf
        kong start -c /etc/kong/kong.conf
      ignore_errors: yes


    - name: Inicia um container de ignicao para popular o banco
      docker_container:
        name: konga_prepara
        image: pantsel/konga:latest
        networks_cli_compatible: yes
        networks:
          - name: host
        command: ["-c", "prepare -a postgres -u postgresql://konga:portprd@aec@127.0.0.1:5432/konga"]
      register: mypass

    - name: Print
      debug:
        var: mypass.stdout_lines


    - name: Inicia o container Konga
      docker_container:
        name: konga_dashboard
        image: pantsel/konga
        networks_cli_compatible: yes
        network_mode: "host"
        env:
          DB_ADAPTER: postgres
          DB_HOST: 127.0.0.1
          DB_PORT: "5432"
          DB_USER: konga
          DB_PASSWORD: portprd@aec
          DB_DATABASE: konga
        ports:
          - "1337:1337"
      register: mypass2

    - name: Print
      debug:
        var: mypass2.stdout_lines


