    - name: Atualiza todos os Pacotes
      apt:
        name: "*"
        state: latest


    - name: Importar Chave
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present



    - name: Adiciona repositorio da versao 7
      ansible.builtin.apt_repository:
          repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
          state: present
          filename: elastic-7.x.list


    - name: Atualiza o Cache
      apt:
        update_cache: yes


        
    - name: Instala pacotes necessarios +  Elastic7 versao 7.11.2
      apt:
        pkg:
        - apt-transport-https
        - unzip
        - elasticsearch=7.11.2


    - name: Cria diretorio de configuracao para tunning de SO
      ansible.builtin.file:
        path: /etc/systemd/system/elasticsearch.service.d/
        state: directory
        mode: '0755'
      tags:
        - create_dir



    -  name: Cria o tunning do SO
       template: src=elasticsearch.conf.j2 dest=/etc/systemd/system/elasticsearch.service.d/elasticsearch.conf
       tags:
         - tunning_so


    -  name: Parametros Gerais de memoria 
       template: src=70-elasticsearch.conf.j2 dest=/etc/sysctl.d/70-elasticsearch.conf
       tags:
         - tunning_memoria


    -  name: Configura YML do Elastic
       template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml
       tags:
         - tunning_yml


    -  name: Configura memoria JVM
       template: src=jvm.options.j2 dest=/etc/elasticsearch/jvm.options
       tags:
         - tunning_java



    - name: Faz reload do daemond para validar as configuracaoes dos servicos
      systemd:
        daemon_reload: yes


    - name: Inicia Elastic
      systemd:
        name: elasticsearch.service
        state: started
        enabled: true

        
    - name: Gerar Senhas automaticas para usuarios de sistema "builtin Users"
      shell: yes | /usr/share/elasticsearch/bin/elasticsearch-setup-passwords auto
      register: mypass

    - name: Print
      debug:
       var:  mypass.stdout_lines

#    - name: Remove Elastic
#      shell: apt-get --purge autoremove elasticsearch -y
#      tags:
#        - remove_elastic

#    - name: Remove diretorios Elastic remanececentes
#      file:
#        state: absent
#        path: "{{item}}"
#      with_items:
#        - /var/lib/elasticsearch/
#        - /etc/elasticsearch
#      tags:
#        - remove_files


    - name:
      debug:
        msg:
          - "1 - EDITE O ARQUIVO /etc/kibana/kibana.yml"
          - "2 - INSIRA NA LINHA ==> elasticsearch.username O USUARIO kibana_system"
          - "3 - INSIRA NA LINHA ==> elasticsearch.password A SENHA GERADA ACIMA PARA O USUARIO kibana_system"
          - "4 - REINICIE O KIBANA APÓS MODIFICACOES ACIMA NO ARQUIVO /etc/kibana/kibana.yml == > systemctl restart kibana"
          - "5 - LOGUE NO KIBANA COM O USUARIO elastic  E A SENHA GERADA PARA ESSE USUARIO"
          - "6 - TROQUE SE PREFERIR A SENHA DE  TODOS OS USUÁRIO APÓS LOGAR NO KIBANA NA OPCAO MANAGER -- > USERS"
          - "7 - VERIFIQUE O LOG EM BUSCA DO TRECHO COM O COMANDO grep -i 'Server running' /var/log/kibana/kibana.log"
      tags:
        - senhas

